export { default as Loading } from './loading'
export { default as MyLayout } from './iframe'
export { default as RenderThumb } from './renderThumb'
export { default as MyUpLoad } from './upload'
export { default as MyPie } from './pie'